[package]
name = "divarel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = "0.7"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
url = "2.2"